src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity=Author::class, inversedBy="article_id")
     */
    private $author_id;

    /**
     * @ORM\ManyToOne(targetEntity=Issue::class, inversedBy="article_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $issue_id;

    /**
     * @ORM\ManyToOne(targetEntity=Genre::class, inversedBy="article_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $genre_id;

    public function __construct()
    {
        $this->author_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Author>
     */
    public function getAuthorId(): Collection
    {
        return $this->author_id;
    }

    public function addAuthorId(Author $authorId): self
    {
        if (!$this->author_id->contains($authorId)) {
            $this->author_id[] = $authorId;
        }

        return $this;
    }

    public function removeAuthorId(Author $authorId): self
    {
        $this->author_id->removeElement($authorId);

        return $this;
    }

    public function getIssueId(): ?Issue
    {
        return $this->issue_id;
    }

    public function setIssueId(?Issue $issue_id): self
    {
        $this->issue_id = $issue_id;

        return $this;
    }

    public function getGenreId(): ?Genre
    {
        return $this->genre_id;
    }

    public function setGenreId(?Genre $genre_id): self
    {
        $this->genre_id = $genre_id;

        return $this;
    }

    public function __toString()
    {
        return strval( $this->getName() );
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('author_id')
            ->add('issue_id')
            ->add('genre_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="app_article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_article_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ArticleRepository $articleRepository): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleRepository->add($article, true);

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_article_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleRepository->add($article, true);

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_article_delete", methods={"POST"})
     */
    public function delete(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $articleRepository->remove($article, true);
        }

        return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Вы уверены, что хотите удалить эту запись?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}"><br>
    <button class="btn">Удалить</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактировать статью{% endblock %}

{% block body %}
    <h1>Редактировать статью</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Обновить'}) }}

    <br><a href="{{ path('app_article_index') }}">Назад к списку</a>

{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Статьи{% endblock %}

{% block body %}
    <h1>Статьи</h1>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Название</th>
                <th>Действие</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.name }}</td>
                <td>
                    <a href="{{ path('app_article_show', {'id': article.id}) }}">Показать</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">Записей не найдено</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_article_new') }}">Создать новую запись</a>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новая статья{% endblock %}

{% block body %}
    <h1>Создать новую статью</h1>

    {{ include('article/_form.html.twig') }}

    <br><a href="{{ path('app_article_index') }}">Назад к списку</a>
{% endblock %}

templates/article/show.html.twig
    {% extends 'base.html.twig' %}

{% block title %}Статья{% endblock %}

{% block body %}
    <h1>Статья</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Название</th>
                <td>{{ article.name }}</td>
            </tr>
            <tr>
                <th>Жанр</th>
                <td>{{ article.genreId }}</td>
            </tr>
            <tr>
                {% if article.authorId.count ==1 %}
                <th>Автор</th>
                {% else %}
                <th>Авторы</th>
                {% endif %}
                <td>{% for author in article.authorId %}
                        {% if author == article.authorId[article.authorId.count-1] %}
                            {{ author }}
                        {% else %}
                            {{ author }},
                        {% endif %}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>В каком выпуске можно найти</th>
                <td>{{ article.issueId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_article_index') }}">Назад к списку</a>

    <a href="{{ path('app_article_edit', {'id': article.id}) }}">Редактировать</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}